server:
  port: 8080

eureka:
  client:
    enabled: false


spring:
  config:
    activate:
      on-profile: prod
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: member-service
#          eureka에 등록된 member-service라는 이름으로 http요청 전
          uri: http://member-service
          predicates:
            - Path=/member/**
          filters:
#            - 첫번째 접두어를 제거한 후 member-service 서버로 http요청 전달
#               유레카의 등록된 이름이 아닌, k8s의 서비스명을 배포시 사용
            - StripPrefix=1
        - id: order-service
          uri: http://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: http://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'https://www.astra1212.shop'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: true
jwt:
  expirationAt: 1000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5Cg==
  expirationRt: 10000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5Cg==
